os: osx
before_install: 
  - touch yarn.lock
  - cd gui
script: yarn build
language: node_js
node_js:
  - "10"
branches:
  only: 
    - master
before_deploy:
- export FILE_TO_UPLOAD=$(ls _releases/-*.dmg)
deploy:
  provider: releases
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true