platform: x64
environment:
  nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:package_version = (Get-Content -Raw -Path gui/electron/package.json | ConvertFrom-Json).version
build_script:
  - cd gui
  - npm run build
before_deploy:
  - cmd: npm run build
deploy:
  release: cloudRIG-v$(package_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: MmTegD+barYJO+vqDJImYT6ui1AhKBsmRRUruCsF0McEGaXKl+zLo5DI94reA9wt
  artifacts: 
    - path: _releases\*
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
