build:
  verbosity: minimal
before_deploy:
  - cmd: npm run publish
deploy:
  release: cloudRIG-$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  artifacts:
    - path: _releases/*.dmg
  auth_token:
    secure: MmTegD+barYJO+vqDJImYT6ui1AhKBsmRRUruCsF0McEGaXKl+zLo5DI94reA9wt # your encrypted token from GitHub
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only