environment:
  nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: $env:package_version = (Get-Content -Raw -Path gui/electron/package.json | ConvertFrom-Json).version
build_script:
  - cd gui
  - npm run build
before_deploy:
  - cmd: npm run build
deploy:
  release: cloudRIG-v$(package_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: MmTegD+barYJO+vqDJImYT6ui1AhKBsmRRUruCsF0McEGaXKl+zLo5DI94reA9wt # your encrypted token from GitHub
  artifact: /.*\.dmg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
