version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - run: sudo apt update && sudo apt install rsync
      - run: yarn install
      - run: cd gui && yarn install
      - run: yarn build --publish=never
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

